export const MAX_LIVES = 5
export const MAX_TOKENS = 5   // display alias — backend field is still `lives`
export const XP_PER_LESSON = 10
export const XP_PER_QUIZ = 5
export const XP_PER_ACCEPTED = 15
export const DEBUG = false

export const GUILD_TICKETS = [
  {
    id: 1,
    user: 'sys_admin_wannabe',
    path: '~/bugs/for-loop.cpp',
    lang: 'C++',
    module: 'control-flow',
    issue: 'Loop never terminates',
    issue_ro: 'Bucla nu se termină',
    body: 'My for-loop runs forever. The compiler stays silent — what am I missing?',
    body_ro: 'For-ul meu rulează la infinit. Compilatorul tace — ce îmi lipsește?',
    codeSnippet: 'for(int i = 0; i < 10 i++) {\n  cout << i << endl;\n}',
    options: ['Add ; after i < 10', 'Replace i++ with ++i', 'Change i < 10 to i <= 10'],
    options_ro: ['Adaugă ; după i < 10', 'Înlocuiește i++ cu ++i', 'Schimbă i < 10 cu i <= 10'],
    correctOptionIndex: 0,
  },
  {
    id: 2,
    user: 'Mira_dev',
    path: '~/bugs/scope.py',
    lang: 'PY',
    module: 'foundations',
    issue: 'NameError: variable used before assignment',
    issue_ro: 'NameError: variabilă folosită înainte de asignare',
    body: 'Python throws NameError even though x is defined inside the function. Why?',
    body_ro: 'Python aruncă NameError deși x este definit în funcție. De ce?',
    codeSnippet: 'def compute():\n    print(x)   # NameError here\n    x = 42\n    return x',
    options: ['Move print(x) after x = 42', 'Add global x at the top of the function', 'Change def compute() to async def compute()'],
    options_ro: ['Mută print(x) după x = 42', 'Adaugă global x la începutul funcției', 'Schimbă def compute() cu async def compute()'],
    correctOptionIndex: 0,
  },
  {
    id: 3,
    user: 'Theo.cpp',
    path: '~/bugs/array-oob.cpp',
    lang: 'C++',
    module: 'algorithms',
    issue: 'Segfault on array fill',
    issue_ro: 'Segfault la umplerea vectorului',
    body: 'Filling arr[5] crashes at runtime. Valgrind says out-of-bounds write — where?',
    body_ro: 'Umplerea arr[5] cade la rulare. Valgrind spune scriere în afara limitelor — unde?',
    codeSnippet: 'int arr[5];\nfor (int i = 0; i <= 5; i++) {\n  arr[i] = i * 2;\n}',
    options: ['Change i <= 5 to i < 5', 'Change int arr[5] to int arr[6]', 'Add arr[5] = 0 initializer'],
    options_ro: ['Schimbă i <= 5 cu i < 5', 'Schimbă int arr[5] cu int arr[6]', 'Adaugă initializatorul arr[5] = 0'],
    correctOptionIndex: 0,
  },
  {
    id: 4,
    user: 'Yusra_py',
    path: '~/bugs/mutation.py',
    lang: 'PY',
    module: 'control-flow',
    issue: 'Loop skips elements after remove()',
    issue_ro: 'Bucla sare elemente după remove()',
    body: 'Removing even numbers mid-loop silently skips some values. What is the safe pattern?',
    body_ro: 'Ștergerea numerelor pare în mijlocul buclei sare unele valori. Care este tiparul sigur?',
    codeSnippet: 'nums = [1, 2, 3, 4, 5, 6]\nfor n in nums:\n    if n % 2 == 0:\n        nums.remove(n)',
    options: ['Use a list comprehension: nums = [n for n in nums if n % 2 != 0]', 'Call nums.sort() before the loop', 'Replace remove(n) with del nums[n]'],
    options_ro: ['Folosește list comprehension: nums = [n for n in nums if n % 2 != 0]', 'Apelează nums.sort() înainte de buclă', 'Înlocuiește remove(n) cu del nums[n]'],
    correctOptionIndex: 0,
  },
  {
    id: 5,
    user: 'ptr_null_error',
    path: '~/bugs/uninit-ptr.cpp',
    lang: 'C++',
    module: 'foundations',
    issue: 'Undefined behaviour on pointer write',
    issue_ro: 'Comportament nedefinit la scrierea prin pointer',
    body: "Writing to *p crashes at runtime. ASan says wild store — what's the fix?",
    body_ro: 'Scrierea prin *p cade la rulare. ASan spune scriere sălbatică — care este reparația?',
    codeSnippet: 'int* p;\n*p = 42;\ncout << *p << endl;',
    options: ['Allocate first: int val = 42; int* p = &val;', 'Cast p to void* before dereferencing', 'Add if (p != nullptr) guard before the write'],
    options_ro: ['Alocă mai întâi: int val = 42; int* p = &val;', 'Convertește p la void* înainte de dereferențiere', 'Adaugă garda if (p != nullptr) înainte de scriere'],
    correctOptionIndex: 0,
  },
]

export const MODULES = [
  {
    id: 'mod_01',
    slug: 'bazele',
    label: 'MOD_01 // BAZELE',
    macro: 'MOD_01 // BAZELE',
    demoStatus: 'unlocked',
    lessons: [
      { id: 'mod01_01', titleKey: 'lessons.mod01_01', status: 'unlocked' },
      { id: 'mod01_02', titleKey: 'lessons.mod01_02', status: 'unlocked' },
      { id: 'mod01_03', titleKey: 'lessons.mod01_03', status: 'unlocked' },
      { id: 'mod01_04', titleKey: 'lessons.mod01_04', status: 'unlocked' },
    ],
  },
  {
    id: 'mod_02',
    slug: 'control',
    label: 'MOD_02 // CONTROL',
    macro: 'MOD_02 // CONTROL',
    demoStatus: 'unlocked',
    lessons: [
      { id: 'mod02_01', titleKey: 'lessons.mod02_01', status: 'unlocked' },
      { id: 'mod02_02', titleKey: 'lessons.mod02_02', status: 'unlocked' },
      { id: 'mod02_03', titleKey: 'lessons.mod02_03', status: 'unlocked' },
    ],
  },
  {
    id: 'mod_03',
    slug: 'elementari',
    label: 'MOD_03 // ELEMENTARI',
    macro: 'MOD_03 // ELEMENTARI',
    demoStatus: 'locked',
    lessons: [
      { id: 'mod03_01', titleKey: 'lessons.mod03_01', status: 'locked' },
      { id: 'mod03_02', titleKey: 'lessons.mod03_02', status: 'locked' },
      { id: 'mod03_03', titleKey: 'lessons.mod03_03', status: 'locked' },
      { id: 'mod03_04', titleKey: 'lessons.mod03_04', status: 'locked' },
    ],
  },
  {
    id: 'mod_04',
    slug: 'vectori',
    label: 'MOD_04 // VECTORI',
    macro: 'MOD_04 // VECTORI',
    demoStatus: 'partial',
    lessons: [
      { id: 'mod04_01', titleKey: 'lessons.mod04_01', status: 'unlocked' },
      { id: 'mod04_02', titleKey: 'lessons.mod04_02', status: 'locked' },
      { id: 'mod04_03', titleKey: 'lessons.mod04_03', status: 'locked' },
      { id: 'mod04_04', titleKey: 'lessons.mod04_04', status: 'unlocked' },
      { id: 'mod04_05', titleKey: 'lessons.mod04_05', status: 'locked' },
      { id: 'mod04_06', titleKey: 'lessons.mod04_06', status: 'locked' },
      { id: 'mod04_07', titleKey: 'lessons.mod04_07', status: 'locked' },
      { id: 'mod04_08', titleKey: 'lessons.mod04_08', status: 'locked' },
    ],
  },
  {
    id: 'mod_05',
    slug: 'matrice',
    label: 'MOD_05 // MATRICE',
    macro: 'MOD_05 // MATRICE',
    demoStatus: 'fog_of_war',
    lessons: [
      { id: 'mod05_01', titleKey: 'lessons.mod05_01', status: 'locked' },
      { id: 'mod05_02', titleKey: 'lessons.mod05_02', status: 'locked' },
    ],
  },
]
